[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Build settings for different contexts
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build:dev"

[context.branch-deploy]
  command = "npm run build:dev"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image optimization
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Primary domain headers
[[headers]]
  for = "https://devnid.xyz/*"
  [headers.values]
    Link = '''</robots.txt>; rel=alternate; type=text/plain, <https://devnid.netlify.app/>; rel=alternate'''
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Alternate domain headers
[[headers]]
  for = "https://devnid.netlify.app/*"
  [headers.values]
    Link = '''</robots.txt>; rel=alternate; type=text/plain, <https://devnid.xyz/>; rel=canonical'''
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Asset headers with CORS
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"

# Image format headers
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

# Redirects for SEO and user experience
[[redirects]]
  from = "/portfolio"
  to = "/"

[[redirects]]
  from = "/services"
  to = "/#expertise"

[[redirects]]
  from = "/projects"
  to = "/#featured-projects"

[[redirects]]
  from = "/about-us"
  to = "/#about"

[[redirects]]
  from = "/contact-us"
  to = "/#contact"

[[redirects]]
  from = "/web-development"
  to = "/"

[[redirects]]
  from = "/full-stack-developer"
  to = "/"

[[redirects]]
  from = "/react-developer"
  to = "/"

[[redirects]]
  from = "/nodejs-developer"
  to = "/"

[[redirects]]
  from = "/old-portfolio"
  to = "/"

[[redirects]]
  from = "/home"
  to = "/"

# 301 redirects for SEO
[[redirects]]
  from = "/portfolio"
  to = "/"
  status = 301

[[redirects]]
  from = "/services"
  to = "/#expertise"
  status = 301

[[redirects]]
  from = "/projects"
  to = "/#featured-projects"
  status = 301

[[redirects]]
  from = "/about-us"
  to = "/#about"
  status = 301

[[redirects]]
  from = "/contact-us"
  to = "/#contact"
  status = 301

[[redirects]]
  from = "/web-development"
  to = "/"
  status = 301

[[redirects]]
  from = "/full-stack-developer"
  to = "/"
  status = 301

[[redirects]]
  from = "/react-developer"
  to = "/"
  status = 301

[[redirects]]
  from = "/nodejs-developer"
  to = "/"
  status = 301

[[redirects]]
  from = "/old-portfolio"
  to = "/"
  status = 301

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cross-domain redirects for SEO
[[redirects]]
  from = "https://devnid.netlify.app/sitemap.xml"
  to = "https://devnid.xyz/sitemap.xml"
  status = 301

[[redirects]]
  from = "https://devnid.netlify.app/robots.txt"
  to = "https://devnid.xyz/robots.txt"
  status = 301

# Edge Functions
[build]
  edge_functions = "netlify/edge-functions"
